name: sharding-repl-cache

services:
  configsvr1:
    image: mongo:7.0
    container_name: configsvr1
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--port", "27019", "--wiredTigerCacheSizeGB", "0.25", "--bind_ip_all"]
    volumes:
      - configsvr1_data:/data/db

  shard1-1:
    image: mongo:7.0
    container_name: shard1-1
    command: ["mongod", "--shardsvr", "--replSet", "shard1rs", "--port", "27018", "--wiredTigerCacheSizeGB", "0.25", "--bind_ip_all"]
    volumes:
      - shard1_1_data:/data/db

  shard1-2:
    image: mongo:7.0
    container_name: shard1-2
    command: ["mongod", "--shardsvr", "--replSet", "shard1rs", "--port", "27018", "--wiredTigerCacheSizeGB", "0.25", "--bind_ip_all"]
    volumes:
      - shard1_2_data:/data/db

  shard1-3:
    image: mongo:7.0
    container_name: shard1-3
    command: ["mongod", "--shardsvr", "--replSet", "shard1rs", "--port", "27018", "--wiredTigerCacheSizeGB", "0.25", "--bind_ip_all"]
    volumes:
      - shard1_3_data:/data/db

  shard2-1:
    image: mongo:7.0
    container_name: shard2-1
    command: ["mongod", "--shardsvr", "--replSet", "shard2rs", "--port", "27018", "--wiredTigerCacheSizeGB", "0.25", "--bind_ip_all"]
    volumes:
      - shard2_1_data:/data/db

  shard2-2:
    image: mongo:7.0
    container_name: shard2-2
    command: ["mongod", "--shardsvr", "--replSet", "shard2rs", "--port", "27018", "--wiredTigerCacheSizeGB", "0.25", "--bind_ip_all"]
    volumes:
      - shard2_2_data:/data/db

  shard2-3:
    image: mongo:7.0
    container_name: shard2-3
    command: ["mongod", "--shardsvr", "--replSet", "shard2rs", "--port", "27018", "--wiredTigerCacheSizeGB", "0.25", "--bind_ip_all"]
    volumes:
      - shard2_3_data:/data/db

  mongos:
    image: mongo:7.0
    container_name: mongos
    depends_on:
      - configsvr1
      - shard1-1
      - shard1-2
      - shard1-3
      - shard2-1
      - shard2-2
      - shard2-3
    command: ["mongos", "--configdb", "configReplSet/configsvr1:27019", "--port", "27017", "--bind_ip_all"]
    ports:
      - "27017:27017"

  redis:
    image: redis:7-alpine
    container_name: redis

  pymongo_api:
    image: kazhem/pymongo_api:1.0.0
    container_name: pymongo_api
    depends_on:
      - mongos
      - redis
    ports:
      - "8080:8080"
    environment:
      MONGODB_URL: "mongodb://mongos:27017"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis:6379"

volumes:
  configsvr1_data:
  shard1_1_data:
  shard1_2_data:
  shard1_3_data:
  shard2_1_data:
  shard2_2_data:
  shard2_3_data:
